version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - mkdir -p test-reports
      - echo "Running tests with coverage..."
      - source venv/bin/activate
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - pytest --junitxml=test-reports/junit-report.xml --cov=.
      - coverage xml -o coverage.xml
      - coverage report --fail-under=40

  post_build:
    commands:
      - echo "Build and tests completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: no

reports:
  junit_reports:
    files:
      - test-reports/junit-report.xml
