version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running tests...
      - pytest --junitxml=report.xml

  post_build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'
  discard-paths: yes
reports:
  pytest_reports:
    files:
      - report.xml
